import { Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../redux/provider";
import Link from "next/link";
import Logout from "../app/logout";
import { getServerSession } from "next-auth";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata = {
  title: "Garisea",
  description: "generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
          <nav>
            {!!session && <Logout />}

            {!session && (
              <Link href={"/login"} className="text-blue-500">
                Login
              </Link>
            )}
          </nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
