import { Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../redux/provider";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "../app/logout"


const poppins = Poppins({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata = {
  title: "Garisea",
  description: "generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
          <nav>
            {!!session &&<Logout/>}

            {!session && <Link href={'/login'}>Login</Link>}
          </nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
