import { Poppins } from "next/font/google";
import './globals.css'
import { ReduxProvider } from "@/redux/provider";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata = {
  title: 'Garisea',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
        {children}
        </ReduxProvider>
        
        </body>
    </html>
  )
}
